Revert "Port to new packaging standards"
This reverts commit 87b23d98c9b2390e1ab70b8deb4d3a694f7068a0.

Causing build failure:
gcc -o .sconf_temp/conftest_3.o -c -Werror -I/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-975@3/utils/rpms/_topdir/BUILDROOT/daos-0.6.0-3.2140.g7b043657.x86_64/include .sconf_temp/conftest_3.c
gcc -o .sconf_temp/conftest_3 -Wl,--enable-new-dtags .sconf_temp/conftest_3.o -lcart -lgurt -lcart
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_epaddr_to_epid@PSM2_1.0'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_ep_disconnect2@PSM2_1.0'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_am_register_handlers_2@PSM2_1.0'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_info_query@PSM2_1.0'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_get_capability_mask@PSM2_1.0'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libfabric.so.1: undefined reference to `psm2_ep_epid_lookup2@PSM2_1.0'
collect2: error: ld returned 1 exit status

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>